# Generated by Django 4.1.7 on 2023-04-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=20)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("group", models.CharField(max_length=20)),
                ("bloodGroup", models.CharField(max_length=20)),
            ],
        ),
    ]
